spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
  jackson:
    default-property-inclusion: NON_NULL

jwt:
  secret: 4@39t1#bEgI6vH$n8oPmA^jF2*lD5uNc7wQzXyZsYxVwAiq%0n8uWm54eU~D3&9$7*j#Bh@I1Y2
  expiration: 999999

# DOC - https://springdoc.org/v2/#migrating-from-springfox
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  # Pacotes que serão escaneados
  packages-to-scan:
    - com.mercadolivro.controller
  # Quais os caminhos que serão adicionados no swagger-ui
  paths-to-match:
    - /books/**
    - /customers/**