spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/mercadolivroprod?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver